### ISSUE TITLE
Drag Item1 from Column1 to Column3, how can it be automatically slid to Column3?

### ISSUE THREAD

**Issue by mvpdream** [lesniakania/react-native-draggable-board#11]
Drag Item1 from Column1 to Column3, how can it be automatically slid to Column3?

**Comment by lesniakania** [comment]
If the column is visible (e.g. in landscape) if should just work. If not, there is no way to do this without dragging it through Column2 in this moment. You could add functionality to scroll the board horizontally when dragged task is on the edge (similar to scrolling a column vertically).
Feel free to open pull request :)
