### ISSUE TITLE
How can I drag an item in Column 1 to Column 3?

### ISSUE THREAD

**Issue by FrozenIce0617** [lesniakania/react-native-draggable-board#15]
I have to drag an item in Column 1 to Column 3 ( it can be Column 5 or 6).
Btw, horizontal auto-scrolling is not working when the item is on the edge.

Please update this feature.

Thanks.

**Comment by lesniakania** [comment]
Hi, I'm sorry, this is very old project of mine, and I don't have time to support it anymore.

**Comment by FrozenIce0617** [comment]
I've fixed it myself.
Moving an item from Column 1 to Column 5 is working well.

**Comment by lesniakania** [comment]
Would you mind making a PR?
