### ISSUE TITLE
Cant install library

### ISSUE THREAD

**Issue by hungdev** [lesniakania/react-native-draggable-board#4]
first, i create new project, it run find. But when i install library by command: npm install react-native-draggable-board
then run react-native run-android, it say error 
![er](https://cloud.githubusercontent.com/assets/12009276/22637199/25b97dd8-ec73-11e6-9853-4987a15045aa.PNG)
Can you help me solve that issue?

**Comment by lesniakania** [comment]
Hi, it does not look like the library issue, to be honest. Are you sure you have react-native packager running? Are you trying to run this on the emulator or on the device? If you run on the device you need to either build and upload a build to the device or setup your packager's host and port on the device - if you shake the device, you will have options for that.

**Comment by hungdev** [comment]
Thank you for reply.
But i dont understand when i run another app, it still fine.
I create new project, it still ok. But when i run command: npm install react-native-draggable-board
then run: react-native run-android, it says error.
Can you push example for me to clone?
Thank you.
![e2](https://cloud.githubusercontent.com/assets/12009276/22682397/0566b578-ed45-11e6-927b-d5b61f0c93c2.PNG)
My package:
![d](https://cloud.githubusercontent.com/assets/12009276/22682418/20fcff7c-ed45-11e6-93f4-3cf47f2e135c.PNG)

**Comment by lesniakania** [comment]
Here is the example: https://github.com/lesniakania/ReactNativeDraggableBoardExample
Let me know if it works for you.

**Comment by hungdev** [comment]
your example (https://github.com/lesniakania/ReactNativeDraggableBoardExample) run ok.
But how do i fix that error when i create new project?

**Comment by hungdev** [comment]
@lesniakania  thank for your support, I have found the error by comparing files and look error.
![dup](https://cloud.githubusercontent.com/assets/12009276/22722376/1c17b174-ede9-11e6-8c9e-8d583a114d8b.PNG)
https://github.com/facebook/jest/issues/771

my file after runcommand: npm install react-native-draggable-board
![file](https://cloud.githubusercontent.com/assets/12009276/22722439/98c144e2-ede9-11e6-8be4-2dedd5ebac10.PNG)
'node_modules' folder  was redundant on patch: \node_modules\react-native-draggable-board
solution: delete 'node_modules' folder then rerun: react-native run-android
