### ISSUE TITLE
Sortable Columns?

### ISSUE THREAD

**Issue by superandrew213** [lesniakania/react-native-draggable-board#5]
Are the columns sortable? Not working for me. Maybe I'm missing something.

**Comment by lesniakania** [comment]
Yes, they are. See https://github.com/lesniakania/ReactNativeDraggableBoardExample.
Can you provide more details how you use the library, so it's not working?

**Comment by superandrew213** [comment]
I used the example you provided but I can't drag the columns. I can drag the rows only.

**Comment by lesniakania** [comment]
Ah, so no, columns themselves are not sortable within a board. Items in the columns are sortable.

**Comment by superandrew213** [comment]
Oh ok, got you. Are you planning to make the columns sortable too?

**Comment by lesniakania** [comment]
Unfortunately not in the near future.

**Comment by onebrunoo** [comment]
is it possible to get the rows inside the columns after sorting? Thank you.

**Comment by lesniakania** [comment]
I need to admit that I did it so long ago, that I don't fully remember, but you can check out [this method](https://github.com/lesniakania/react-native-draggable-board/blob/master/src/lib/RowRepository.js#L24). I think you should be able to use it, I can try to help more if you have issues, but I need I have really crazy time right now, so I might have delays. I don't support this library anymore : /
