### ISSUE TITLE
Dragging card bugs

### ISSUE THREAD

**Issue by mattiasmak** [lesniakania/react-native-draggable-board#6]
When dragging a card vertically it gets "stuck" and instead the Scrollview starts to scroll.  However If I keep the drag just in the x-axis it seems to work fine.

**Comment by mattiasmak** [comment]
I'm running this in Simulator. Will test in phone

**Comment by lesniakania** [comment]
Can you record a gif?

**Comment by mattiasmak** [comment]
![2017-04-03 09 50 39](https://cloud.githubusercontent.com/assets/606639/24600037/23a5e52a-1853-11e7-8ea4-a9b458d21461.gif)

**Comment by lesniakania** [comment]
Ok, so this is weird indeed. Is it the last version? Can you provide me with the exact version of the library, react and react-native?

**Comment by mattiasmak** [comment]
```
{
  "name": "ColabMobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.0.12",
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-draggable-board": "^1.1.0",
    "react-native-drawer": "^2.3.0",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-popup-menu": "^0.7.2",
    "react-native-side-menu": "^0.20.1"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.1",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by mattiasmak** [comment]
I can debug this myself also. Could be something with native-base that wraps the draggable-board... Can you recommend were to look?

**Comment by lesniakania** [comment]
Yeah, could be that... I think I would start from the [ExampleApp](https://github.com/lesniakania/ReactNativeDraggableBoardExample) and I would add your wrapping components one by one and see what's breaking stuff. Unfortunately, this whole PanResponder thing is really sensitive in terms of composing in too many elements.

If you could debug it on your own, it would be awesome, cause I'm a bit overwhelmed right now.
But I would be happy to guide you and answer questions.

**Comment by mattiasmak** [comment]
Now it works perfect.  Removed a few wrapping elements. :)

**Comment by lesniakania** [comment]
Awesome to hear : ) If you have any feedback, feel free to share. It works in my case, but I'm curious how it's reusable for others.
